option('mmmcolorfmt', type : 'boolean', value : 'true', yield : true, description: 'Use display mmm_color_fmts enum')
option('useumd', type : 'boolean', value : 'false', yield : true, description: 'Use umd')
option('ASAN', type: 'boolean', value: false, description: 'Enable address sanitizers tool')
